name: "🐛 Copilot Agent Task - Bug Fix"
description: "Template for assigning bug fix tasks to GitHub Copilot"
title: "[Copilot Bug Fix] Fix [Bug Description]"
labels: ["copilot-task", "bug", "needs-fix"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🤖 Copilot Agent Bug Fix Assignment
        
        **📖 Reference**: See `.github/copilot-instructions.md` for comprehensive project guidance, architecture details, and development standards.

  - type: input
    id: bug-summary
    attributes:
      label: "Bug Summary"
      description: "Brief description of the bug"
      placeholder: "e.g., Product search returns duplicate results"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Bug Severity"
      description: "How severe is this bug?"
      options:
        - "🔴 Critical - System broken, blocking operations"
        - "🟠 High - Major functionality impacted"
        - "🟡 Medium - Some functionality impacted"
        - "🟢 Low - Minor issue, cosmetic problem"
    validations:
      required: true

  - type: dropdown
    id: affected-component
    attributes:
      label: "Affected Component"
      description: "Which part of the system is affected?"
      options:
        - "Backend API"
        - "Frontend UI"
        - "Database Layer"
        - "Authentication"
        - "Business Logic"
        - "Infrastructure/DevOps"
        - "Testing"
        - "Multiple Components"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: "Steps to Reproduce"
      description: "Provide clear steps to reproduce the bug"
      placeholder: |
        1. Go to the products page
        2. Enter 'laptop' in the search box
        3. Click the search button
        4. Observe duplicate entries for the same product
    validations:
      required: true

  - type: textarea
    id: expected-vs-actual
    attributes:
      label: "Expected vs Actual Behavior"
      description: "What should happen vs what actually happens?"
      placeholder: |
        **Expected**: Search returns unique products only
        **Actual**: Search returns duplicate entries for the same product
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: "Error Logs/Stack Traces (if any)"
      description: "Include relevant error messages or stack traces"
      placeholder: |
        ```
        System.InvalidOperationException: Sequence contains duplicate elements
           at DemoInventory.Application.Services.ProductService.SearchProducts(String searchTerm)
        ```

  - type: textarea
    id: affected-files
    attributes:
      label: "Suspected Affected Files"
      description: "List files that might be related to this bug"
      placeholder: |
        - `backend/src/DemoInventory.Application/Services/ProductService.cs`
        - `frontend/src/components/ProductSearch.tsx`

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Environment details, investigation notes, or proposed solutions"
      placeholder: |
        - Environment: Development/Docker/Production
        - Recent changes that might have caused this
        - Any debugging already performed
        - Potential solutions considered

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 📋 For Copilot Agent
        
        1. **Analyze the root cause** - Don't just fix symptoms
        2. **Write tests first** - Create failing tests that reproduce the bug  
        3. **Fix systematically** - Make minimal changes to address the root cause
        4. **Verify thoroughly** - Ensure fix works and doesn't break existing functionality
        
        **📖 Full project guidance**: `.github/copilot-instructions.md` contains comprehensive details on architecture, coding standards, testing strategy, and development workflow.